# Generated by Django 5.0.4 on 2026-04-15 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (emoji или class)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержимое статьи')),
                ('category', models.CharField(choices=[('basics', 'Основы ИИ'), ('prompts', 'Промпт-инжиниринг'), ('tools', 'Инструменты'), ('education', 'ИИ в образовании'), ('ethics', 'Этика и безопасность')], max_length=50, verbose_name='Категория гайда')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Статья гайдбука',
                'verbose_name_plural': 'Статьи гайдбука',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('system_prompt', models.TextField(help_text='Базовая инструкция для языковой модели', verbose_name='Системный промпт (инструкция для ИИ)')),
                ('user_prompt_template', models.TextField(help_text='Используйте {variable} для подстановки ответов пользователя', verbose_name='Шаблон пользовательского промпта')),
                ('variables', models.JSONField(default=list, help_text="Список переменных: [{'name': 'subject', 'label': 'Предмет'}]", verbose_name='Переменные шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шаблон промпта',
                'verbose_name_plural': 'Шаблоны промптов',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_data', models.JSONField(default=dict, verbose_name='Контекст (ответы пользователя)')),
                ('generated_prompt', models.TextField(verbose_name='Сгенерированный промпт')),
                ('ai_model', models.CharField(choices=[('qwen', 'Qwen'), ('gpt-4', 'GPT-4'), ('claude', 'Claude'), ('other', 'Другая')], default='qwen', max_length=50, verbose_name='ИИ-модель')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В избранном')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Категория')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='core.prompttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный промпт',
                'verbose_name_plural': 'Сгенерированные промпты',
                'ordering': ['-created_at'],
            },
        ),
    ]
